type: haystack.components.embedders.sentence_transformers_document_embedder.SentenceTransformersDocumentEmbedder
init_parameters:
  model: ???
  normalize_embeddings: ???
  device: ${runtime.device}
  progress_bar: ${runtime.progress_bar}
  tokenizer_kwargs: ???
