# @package _global_

defaults:
  - /paths: local
  - /dataset: ???
  - _self_

stage:
  name: evaluation
  run_name: null
  inference_run_id: null
  run_id: ${now:%Y%m%d_%H%M%S_%f}
  output_dir: ${paths.runs_dir}/${stage.name}/${stage.run_id}
  predictions_path: null
  metrics_path: ${stage.output_dir}/metrics.json

metrics:
  - Recall@10
  - Recall@50
  - Recall@100
  - MRR@50
  - NDCG@10
  - HitRate@10

hydra:
  job:
    chdir: false
  run:
    dir: ${paths.runs_dir}/hydra/${stage.name}/${stage.run_id}
