# @package _global_

defaults:
  - /paths: local
  - /dataset: ???
  - /pipeline/indexing@pipeline: ???
  - /runtime: ???
  - _self_

stage:
  name: indexing
  run_id: ${now:%Y%m%d-%H%M%S-%f}
  output_dir: ${paths.runs_dir}/${stage.name}/${stage.run_id}
