# @package _global_

defaults:
  - /paths: local
  - /dataset: ???
  - /input_mapping_recipe: ???
  - _self_

stage:
  name: prepare_mapping
  run_id: ???
  output_dir: ${paths.runs_dir}/${stage.name}/${stage.run_id}
