type: retrieval_components.retrieval.jsonl_embedding_retriever.JsonlEmbeddingRetriever
init_parameters:
  index_path: ${stage.index_path}
  top_k: 5
  similarity: ${selections.embedding_model.similarity}
