type: retrieval_components.models.sentence_transformers_similarity_ranker.SentenceTransformersSimilarityRanker
init_parameters:
  model: ???
  device: ${runtime.device}
  top_k: 10
  scale_score: ???
  tokenizer_kwargs: ???
