metadata:
  description: Use every query, but only documents with qrel annotations for that query.

type: generated
name: judged_only
seed: 0
query_subset_size: null
document_subset_size: null
random_docs_per_query: 0
easy_negative_docs_per_query: 0
gold_passage_docs_per_query: 0
