name: toy
documents_path: ${paths.project_root}/datasets/toy/documents.jsonl
queries_path: ${paths.project_root}/datasets/toy/queries.jsonl
qrels_path: ${paths.project_root}/datasets/toy/qrels.jsonl
input_mapping_path: ${paths.project_root}/datasets/toy/input_mapping.json
