name: toy
documents_path: ${paths.processed_data_dir}/toy/documents.jsonl
queries_path: ${paths.processed_data_dir}/toy/queries.jsonl
qrels_path: ${paths.processed_data_dir}/toy/qrels.jsonl
input_mapping_path: ${paths.processed_data_dir}/toy/input_mapping.json
