# @package _global_
defaults:
  - /stages/inference
  - override /dataset: {{ cookiecutter.dataset_config }}
  - override /pipeline/inference@pipeline: {{ cookiecutter.baseline_pipeline }}
  - override /selections/embedding_model@selections.embedding_model: {{ cookiecutter.embedding_model }}
  - override /runtime: {{ cookiecutter.runtime_config }}
  - _self_

selections:
  index_id: {{ cookiecutter.index_id | tojson }}

pipeline:
  components:
    retriever:
      init_parameters:
        top_k: {{ cookiecutter.retrieval_top_k }}
