type: retrieval_components.models.sentence_transformers_text_embedder.SentenceTransformersTextEmbedder
init_parameters:
  model: ???
  normalize_embeddings: ???
  device: ${runtime.device}
  progress_bar: ${runtime.progress_bar}
  tokenizer_kwargs: ???
