type: sparse_autoencoder_retrieval.components.SparseAutoencoderTextEmbedder
init_parameters:
  model: ???
  autoencoder_path: ???
  device: ${runtime.device.device}
  batch_size: 32
  normalize_embeddings: ???
  progress_bar: ${runtime.progress_bar}
