type: retrieval_research.components.retrieval.jsonl_embedding_retriever.JsonlEmbeddingRetriever
init_parameters:
  index_path: ${paths.index_dir}/${dataset.name}_${selections.embedding_model.artifact_name}.jsonl
  top_k: ${retrieval.top_k}
  similarity: ${selections.embedding_model.similarity}
