type: retrieval_research.components.jsonl_document_indexer.JsonlDocumentIndexer
init_parameters:
  output_path: ${paths.index_dir}/${dataset.name}_${selections.embedding_model.artifact_name}.jsonl
  overwrite: true
